CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);
CREATE TABLE Jogos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
    Genero VARCHAR(255) NOT NULL,
    Preco FLOAT NOT NULL
);

ALTER TABLE Jogos
ADD Imagem  TEXT NULL ;

ALTER TABLE Jogos
ADD arquivo_jogo  TEXT NULL;

ALTER TABLE Jogos
ADD Imagem_jogo TEXT NULL;

ALTER TABLE Jogos
ADD logo_jogo TEXT NULL;

ALTER TABLE Jogos
DROP COLUMN Imagem;